# Generated by Django 5.2.1 on 2026-03-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
